### ISSUE TITLE
Not run the github-dork.py  exucutable file

### ISSUE THREAD

**Issue by sushantdhopat19** [techgaun/github-dorks#40]
first i install the github-dork with git clone then i install all requirements with pip then i make the github-dork.py exucuable and write help cmd ./gitthub-dork.py -h is give me error this 

Traceback (most recent call last):
  File "./github-dork.py", line 4, in <module>
    import github3 as github
  File "build/bdist.linux-x86_64/egg/github3/__init__.py", line 24, in <module>
  File "build/bdist.linux-x86_64/egg/github3/api.py", line 13, in <module>
  File "build/bdist.linux-x86_64/egg/github3/github.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/github3/apps.py", line 7, in <module>
ImportError: No module named jwcrypto

i also install this module sepretlly with pip this say seccessfull install it but he give also same error

**Comment by techgaun** [comment]
Hi @sushantdhopat19 what python version are you using? And, are you still receiving same error even after you install jwcrypto?

**Comment by sushantdhopat19** [comment]
This tool run and work properly when I  use Python3  but give me every time sleep error what this is default ?I will not use it for a long time .Still he give me this error .

**Comment by yrrahsilieb** [comment]
>50

**Comment by techgaun** [comment]
@sushantdhopat you can use the github personal access token for getting higher rate limit. This tool is limited by the rate limiting headers from github so it tries to oblige and wait until the rate limit is freed up.

**Comment by Harshj054** [comment]
Can you help me solve this error
python3 github-dork.py -r https://github.com/techgaun/github-dorks
Scanning Repo:  https://github.com/techgaun/github-dorks
GitHubError encountered on search of dork: filename:.npmrc _auth repo:https://github.com/techgaun/github-dorks
422 Validation Failed

**Comment by SaraVijay123** [comment]
i am also facing the same error.
GitHubError encountered on search of dork: filename:.npmrc _auth repo:https://github.com/techgaun/github-dorks
422 Validation Failed.

Help me in solving this .
