### ISSUE TITLE
AttributeError: module 'base64' has no attribute 'decodestring'

### ISSUE THREAD

**Issue by 0xn0ne** [techgaun/github-dorks#43]
hello! when i run this script, i got this problem.

```
> python .\github-dork.py
Traceback (most recent call last):
  File "C:\***\github-dorks-master\github-dork.py", line 8, in <module>
    import feedparser
  File "C:\***\AppData\Roaming\Python\Python39\site-packages\feedparser.py", line 106, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
```

this is my env:

```
> python -V
Python 3.9.0

> systeminfo

主机名:           ***
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.19042 暂缺 Build 19042
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     ***
注册的组织:
产品 ID:          ***
初始安装日期:     ***
系统启动时间:     2021/1/1, 1:21:19
系统制造商:       ASUSTeK COMPUTER INC.
系统型号:         ROG Zephyrus G14 GA401IV_GA401IV
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: AMD64 Family 23 Model 96 Stepping 1 AuthenticAMD ~2900 Mhz
BIOS 版本:        American Megatrends Inc. GA401IV.218, 2020/11/5
Windows 目录:     ***
系统目录:         ***
启动设备:         ***
```

**Comment by techgaun** [comment]
Hi @0xn0ne thanks for the issue. This is a result of feedparser using `base64.decodestrings` which was deprecated and now removed in python 3.9. The upstream feedparser library has now been updated, however it would not work with python2. Given that python2 has been sunsetted since about a year, I'm going to no longer have this tool python2 compatible and will upgrade feedparser soon.

**Comment by 0xn0ne** [comment]
Thanks for providing such a great tool!
